version: '3.8'
services:
  frontend:
    build: .
    container_name: referenced-payments-frontend
    ports:
      - "4200:80"
    restart: always
    networks:
      - referenced-network

networks:
  referenced-network:
    external: true